### PR TITLE
Dall-E section

### LINKED ISSUE #12: Write Dall-E section
Write the section about Dall-E

### PR DESCRIPTION
**Pull request by EhrenbruderRoschtbraten**
Wrote the Dall-E image generation section. 

closes #12

### CODE REVIEW

**Review by RaphaW — APPROVED** [review]
lgtm

**Review by 1Maxnet1 — COMMENTED** [review]
Looks good to me, which version did we use ? Because the link mentions version 3, but the text does not mention which version we used.

**Comment by EhrenbruderRoschtbraten** [comment]
> Looks good to me, which version did we use ? Because the link mentions version 3, but the text does not mention which version we used.

I guess it should be 3, I added it

**Review by 1Maxnet1 — APPROVED** [review]
LGTM

**Pull request merged**
