### PR TITLE
Make sections clearer

### PR DESCRIPTION
**Pull request by RaphaW**
These are just some minor adjustments to make the different sections clearer
Made the different keywords bold

### CODE REVIEW

**Review by 1Maxnet1 — COMMENTED** [review]
Looks good to me. However I have a general issue, regarding the double backslash. At some point I read that they are considered bad style and lead to warnings, so I would rather use newlines instead. See also here: https://tex.stackexchange.com/questions/225893/what-does-double-backslash-in-latex-mean

**Review by EhrenbruderRoschtbraten — CHANGES_REQUESTED** [review]
Looks good, but maybe we can here also move the text generative models above the image generative ones, since @1Maxnet1 did it also this way round in the branch, where he adjusted the detecting models.

**Comment by RaphaW** [comment]
> Looks good, but maybe we can here also move the text generative models above the image generative ones, since @1Maxnet1 did it also this way round in the branch, where he adjusted the detecting models.

No I would not, since this is the order of the figures as well. I would rather change it in the sections you mentioned if they are different

**Review by 1Maxnet1 — APPROVED** [review]
LGTM

**Review by EhrenbruderRoschtbraten — APPROVED** [review]

**Review by LeviUniAcc — APPROVED** [review]

**Pull request merged**
