### PR TITLE
Extended the image detection part

### LINKED ISSUE #39: Write Section about image-generating model detector

### PR DESCRIPTION
**Pull request by EhrenbruderRoschtbraten**
Added two sections about image detection models, namely the Is It AI model an the Advanced AI Image Detector.

closes #39

### CODE REVIEW

**Review by 1Maxnet1 — APPROVED** [review]
LGTM

**Review by LeviUniAcc — COMMENTED** [review]
is it possible to get some more information about the availability, like is it free (if not how expensive) or open source or somethink like that? otherwise i think its good.

**Comment by EhrenbruderRoschtbraten** [comment]
> is it possible to get some more information about the availability, like is it free (if not how expensive) or open source or somethink like that? otherwise i think its good.

I added, that they are freely usable through a web interface.

**Review by RaphaW — APPROVED** [review]
lgtm

**Review by LeviUniAcc — APPROVED** [review]

**Pull request merged**
